<a href="https://colab.research.google.com/github/joseraz/data_science_journey/blob/master/numpy_warmup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [4]:
L = [1, 5, 7, 9]
s = np.array(L)
print(s)
new_list = list(s)
print(new_list)

[1 5 7 9]
[1, 5, 7, 9]


In [5]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
m.ndim

2

In [7]:
m.shape

(3, 3)

In [17]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])
print(b.ndim)
print(b.shape)


2
(4, 3)


In [19]:
help(np.ndim)

Help on function ndim in module numpy:

ndim(a)
    Return the number of dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.  If it is not already an ndarray, a conversion is
        attempted.
    
    Returns
    -------
    number_of_dimensions : int
        The number of dimensions in `a`.  Scalars are zero-dimensional.
    
    See Also
    --------
    ndarray.ndim : equivalent method
    shape : dimensions of array
    ndarray.shape : dimensions of array
    
    Examples
    --------
    >>> np.ndim([[1,2,3],[4,5,6]])
    2
    >>> np.ndim(np.array([[1,2,3],[4,5,6]]))
    2
    >>> np.ndim(1)
    0



In [20]:
b.size

12

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [24]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [27]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [29]:
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [31]:
np.random.rand(3,5)

array([[0.77348303, 0.00139734, 0.82401929, 0.88320226, 0.37058309],
       [0.91725855, 0.9792661 , 0.47655477, 0.36247914, 0.44232772],
       [0.66625013, 0.42117917, 0.71834674, 0.41721128, 0.14193088]])

In [0]:
a = np.array([[1, 2, 3],
              [4, 5, 4],
              [3, 2, 1]])

In [33]:
a+2

array([[3, 4, 5],
       [6, 7, 6],
       [5, 4, 3]])

In [34]:
a*3

array([[ 3,  6,  9],
       [12, 15, 12],
       [ 9,  6,  3]])

In [35]:
a**2

array([[ 1,  4,  9],
       [16, 25, 16],
       [ 9,  4,  1]])

In [36]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 2. ],
       [1.5, 1. , 0.5]])

In [37]:
a*a

array([[ 1,  4,  9],
       [16, 25, 16],
       [ 9,  4,  1]])

In [39]:
np.cos(a) #cosine function

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219, -0.65364362],
       [-0.9899925 , -0.41614684,  0.54030231]])

In [41]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 ,  54.59815003],
       [ 20.08553692,   7.3890561 ,   2.71828183]])

In [45]:
b = np.array([1, 3, 5])
print(sum(b))
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(np.sum(a, axis =0)) # This takes the sums of the colums
print(np.sum(a, axis =1)) # This takes the sums of the rows
print([min(b), max(b)])
print(np.max(a, axis =0)) # This takes the max of each colums
print(np.min(a, axis =1)) # this one the max of each row

9
[ 9 12]
[ 3  7 11]
[1, 5]
[5 6]
[1 3 5]


Numpy has a large number of these functions available, some of which are included in the following table. Most of these functions come with "NaN-safe" counterpart. A NaN-safe function can deal with missing values (which are called NaN values for "Not a Number") bye ignoring them and not returning an error.